channels:
- conda-forge
dependencies:
- python=3.11.5
- pip<=23.3.1
- pip:
  - mlflow==2.9.2
  - cloudpickle==3.0.0
  - numpy==1.26.3
  - packaging==23.1
  - pandas==2.1.4
  - pyyaml==6.0.1
  - torch==2.1.2
name: mlflow-env
